include: package:flutter_lints/flutter.yaml
analyzer:
  exclude:
    - "**/*.g.dart"
    - "**/*.config.dart"
linter:
  rules:
    prefer_single_quotes: true
    always_put_required_named_parameters_first: true
    require_trailing_commas: true
    always_use_package_imports: true