name: altitude
description: A new Flutter project.

version: 3.2.0

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  get_it: ^5.0.6
  injectable: ^1.1.2
  package_info: ^0.4.0+13
  sqflite: ^1.1.7+1
  table_calendar: ^2.1.0
  fluttertoast: ^3.1.3
  flutter_keyboard_visibility: ^2.0.0
  shared_preferences: ^0.5.6+3
  numberpicker: ^1.0.0
  flutter_local_notifications: ^5.0.0
  vibration: ^1.2.2
  auto_size_text: ^2.0.2+1
  firebase_core: any
  firebase_auth: ^1.0.1
  firebase_analytics: ^5.0.11
  firebase_messaging: ^9.1.0
  firebase_crashlytics: ^1.0.0
  cloud_firestore: ^1.0.3
  cloud_functions: ^1.0.2
  # flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.1
  url_launcher: ^6.0.3
  shimmer: ^1.1.1
  fl_chart: ^0.10.0
  google_mobile_ads: ^0.12.0

dev_dependencies:
  mobx_codegen:
  build_runner: any
  flutter_test:
    sdk: flutter
  mockito: any
  injectable_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/level/

  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Regular.ttf
          - asset: fonts/Montserrat-Bold.ttf
            weight: 700
          - asset: fonts/Montserrat-Light.ttf
            weight: 300
            