name: altitude
description: A new Flutter project.

version: 2.1.8

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  get_it: ^4.0.1
  package_info: ^0.4.0+13
  sqflite: ^1.1.7+1
  table_calendar: ^2.1.0
  fluttertoast: ^3.1.3
  flutter_keyboard_visibility: ^2.0.0
  shared_preferences: ^0.5.6+3
  numberpicker: ^1.0.0
  flutter_local_notifications: ^0.9.1+1
  vibration: ^1.2.2
  sliding_up_panel: ^0.3.6
  auto_size_text: ^2.0.2+1
  firebase_core: ^0.4.4+3
  firebase_auth: ^0.16.0
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  cloud_functions: ^0.4.2+3
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.1
  url_launcher: ^5.4.5
  shimmer: ^1.1.1

dev_dependencies:
  mobx_codegen:
  build_runner:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/level/

  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Regular.ttf
          - asset: fonts/Montserrat-Bold.ttf
            weight: 700
          - asset: fonts/Montserrat-Light.ttf
            weight: 300
            