name: altitude
description: A new Flutter project.

version: 3.2.0

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  # state management
  flutter_mobx: 2.0.4
  mobx: 2.0.6+1
  # dependecy injection
  get_it: 7.2.0
  injectable: 1.5.3
  # local database
  shared_preferences: 2.0.13
  sqflite: 2.0.2
  # firebase
  firebase_core: 1.13.1
  firebase_auth: 3.3.11
  firebase_analytics: 9.1.2
  firebase_messaging: 11.2.11
  firebase_crashlytics: 2.5.3
  cloud_firestore: 3.1.10
  cloud_functions: 3.2.10
  # login
  # flutter_facebook_login: ^3.0.0
  google_sign_in: 5.2.4
  # ads
  google_mobile_ads: 1.1.0
  # widgets
  table_calendar: 3.0.5
  numberpicker: 2.1.1
  auto_size_text: 3.0.0
  shimmer: 2.0.0
  fl_chart: 0.50.0
  fluttertoast: 8.0.9
  # others
  package_info: 2.0.2
  flutter_keyboard_visibility: 5.2.0
  flutter_local_notifications: 5.0.0+4
  vibration: 1.7.4-nullsafety.0
  url_launcher: 6.0.20

dev_dependencies:
  flutter_test:
    sdk: flutter
  mobx_codegen: 2.0.5+2
  build_runner: 2.1.8
  mockito: 5.1.0
  injectable_generator: 1.5.3
  flutter_lints: ^1.0.4

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/level/

  fonts:
    - family: Montserrat
      fonts:
        - asset: fonts/Montserrat-Regular.ttf
        - asset: fonts/Montserrat-Bold.ttf
          weight: 700
        - asset: fonts/Montserrat-Light.ttf
          weight: 300
