name: altitude
description: A new Flutter project.

version: 3.0.3

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  flutter_mobx: ^1.1.0
  mobx: ^1.1.1
  get_it: ^5.0.6
  injectable: ^1.1.2
  package_info: ^0.4.0+13
  sqflite: ^1.1.7+1
  table_calendar: ^2.1.0
  fluttertoast: ^3.1.3
  flutter_keyboard_visibility: ^2.0.0
  shared_preferences: ^0.5.6+3
  numberpicker: ^1.0.0
  flutter_local_notifications: ^1.4.4+2
  vibration: ^1.2.2
  sliding_up_panel: ^0.3.6
  auto_size_text: ^2.0.2+1
  firebase_core: ^0.5.0
  firebase_auth: ^0.18.0+1
  firebase_analytics: ^5.0.11
  firebase_messaging: ^6.0.13
  firebase_remote_config: ^0.3.0+3
  firebase_crashlytics: ^0.2.1+1
  cloud_firestore: ^0.14.0+1
  cloud_functions: ^0.6.0
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.4.1
  url_launcher: ^5.4.5
  shimmer: ^1.1.1
  fl_chart: ^0.10.0
  google_mobile_ads: ^0.11.0+4

dev_dependencies:
  mobx_codegen:
  build_runner: any
  flutter_test:
    sdk: flutter
  mockito: any
  injectable_generator: any

flutter:
  uses-material-design: true
  assets:
    - assets/
    - assets/level/

  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Regular.ttf
          - asset: fonts/Montserrat-Bold.ttf
            weight: 700
          - asset: fonts/Montserrat-Light.ttf
            weight: 300
            