name: altitude
description: A new Flutter project.

version: 2.1.4

environment:
  sdk: ">=2.6.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^0.1.2
  provider: ^4.0.4
  package_info: ^0.4.0+13
  sqflite: ^1.1.7+1
  table_calendar: ^2.1.0
  fluttertoast: ^3.1.3
  keyboard_visibility: ^0.5.6
  shared_preferences: ^0.5.6
  numberpicker: ^1.0.0
  flutter_local_notifications: ^0.9.1+1
  vibration: ^1.2.2
  sliding_up_panel: ^0.3.6
  auto_size_text: ^2.0.2+1
  firebase_core: ^0.4.3+1
  firebase_auth: ^0.15.3
  firebase_analytics: ^5.0.9
  firebase_messaging: ^6.0.9
  cloud_functions: ^0.4.1+6
  flutter_facebook_login: ^3.0.0
  google_sign_in: ^4.1.1
  url_launcher: ^5.2.1
  shimmer: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  assets:
    - assets/first.png
    - assets/second.png
    - assets/third.png
    - assets/ic_award.png
    - assets/smoke.png
    - assets/cloud1.png
    - assets/cloud2.png
    - assets/finger.png
    - assets/createHabit.png
    - assets/completeHabit.png
    - assets/score.png
    - assets/level/gold1.png
    - assets/level/gold2.png
    - assets/level/gold3.png
    - assets/level/silver1.png
    - assets/level/silver2.png
    - assets/level/silver3.png
    - assets/level/bronze0.png
    - assets/level/bronze1.png
    - assets/level/bronze2.png
    - assets/level/bronze3.png

  fonts:
      - family: Montserrat
        fonts:
          - asset: fonts/Montserrat-Regular.ttf
          - asset: fonts/Montserrat-Bold.ttf
            weight: 700
          - asset: fonts/Montserrat-Light.ttf
            weight: 300
            