// App
const VERSION = "VERSION";
// User data
const String NAME = "USER_NAME";
const String SCORE = "USER_SCORE";
const String LEVEL = "USER_LEVEL";
const String HABIT_FILTERS = "USER_HABIT_FILTERS";
const String PENDING_FRIENDS = "USER_PENDING_FRIENDS";
const String COMPETITION_FRIENDS = "USER_COMPETITION_FRIENDS";
const String NEW_LEARN_TEXT = "NEW_LEARN_TEXT";
const String PENDING_STATISTICS = "PENDING_STATISTICS";
// Tutorials
const String HABIT_TUTORIAL = "HABIT_TUTORIAL";
const String COMPETITION_TUTORIAL = "COMPETITION_TUTORIAL";
const String ROCKET_ON_DETAILS_PAGE = "ROCKET_ON_DETAILS_PAGE";
const String ALARM_ON_DETAILS_PAGE = "ALARM_ON_DETAILS_PAGE";